name: frontend-ci-cd
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: [ 22 ]
    steps:
      - name: test secrets
        run: echo "password is ${{ secrets.VPS_PASSWORD  }}"


